// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjqEpLZE4B8qDYf6Vn7kkrqGHejcPsQNk',
    appId: '1:307056666844:web:46f45168f3e37b42b36c19',
    messagingSenderId: '307056666844',
    projectId: 'jimiker-ssdev',
    authDomain: 'jimiker-ssdev.firebaseapp.com',
    storageBucket: 'jimiker-ssdev.firebasestorage.app',
    measurementId: 'G-FCV8QFF7EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGdGO7UYnz058HpY8w6Sc-u_n471KwjKI',
    // com.jimiker2.app 으로 등록된 앱.
    // (com.example.jimiker · com.jimiker.app 시절 앱은 쓰지 않는다)
    appId: '1:307056666844:android:440489dee2c2d8c2b36c19',
    messagingSenderId: '307056666844',
    projectId: 'jimiker-ssdev',
    storageBucket: 'jimiker-ssdev.firebasestorage.app',
  );

  // iOS는 아직 손대지 않았다. GoogleService-Info.plist도 없고 APNs도
  // 설정 전이라, 지금 번들 id만 바꾸면 Firebase에 등록된 iOS 앱
  // (com.example.jimiker)과 어긋나기만 한다.
  // iOS를 실제로 낼 때 Firebase에 iOS 앱을 새로 등록하고 여기까지 함께 고칠 것.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe6BaU5p-FHklTbpq-9vYJHLv50E1-DXw',
    appId: '1:307056666844:ios:3b04f19968717ea7b36c19',
    messagingSenderId: '307056666844',
    projectId: 'jimiker-ssdev',
    storageBucket: 'jimiker-ssdev.firebasestorage.app',
    iosBundleId: 'com.example.jimiker',
  );
}
